
package com.weather.service.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.3.1-patch-01
 * Wed Jul 28 10:13:06 IST 2021
 * Generated source version: 2.3.1-patch-01
 */

@XmlRootElement(name = "gettemperature", namespace = "http://service.weather.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "gettemperature", namespace = "http://service.weather.com/")

public class Gettemperature {

    @XmlElement(name = "arg0")
    private int arg0;

    public int getArg0() {
        return this.arg0;
    }

    public void setArg0(int newArg0)  {
        this.arg0 = newArg0;
    }

}

